### ISSUE TITLE
imprecise coords

### ISSUE THREAD

**Issue by sckott** [ropensci/scrubr#18]
idea is to clean coordinates that are imprecise

e.g., `-117, 35` and `-117.000, 35.000` are not reliable, so remove/flag those

we'd have to make some rules: e.g;

**Comment by snsheth** [comment]
1) flag latitude or longitude coordinates without decimal places 
2) flag latitude or longitude coordinates with only 0s after the decimal

**Comment by sckott** [comment]
Thanks, those sound good, and easy to do, probably.

**Comment by sckott** [comment]
@snsheth sorry for the very long wait, reinstall `devtools::install_github("ropenscilabs/scrubr")` and see egs. at https://github.com/ropenscilabs/scrubr/blob/master/R/coord-funs.R#L60-L74

any other use cases?  does it do what you want?

**Comment by snsheth** [comment]
Thanks so much for including these! I just tried out the updated function, and I realize now that I miscommunicated in my comment on March 17. I should've used "and" instead of "or", such that rows whose latitude & longitude both meet the criteria below are flagged:

1) flag latitude and longitude coordinates without decimal places 
2) flag latitude and longitude coordinates with only 0s after the decimal

Thanks again. This is very useful.

**Comment by sckott** [comment]
@snsheth thanks for the feedback. Do you feel like you'd use a function that did `AND` and a function that did `OR`, or only the former?

**Comment by snsheth** [comment]
I think I'd more likely use a function that did AND, but I'd be curious to hear what other end users think. I am more suspicious of coordinates where lat & lon are rounded, then those in which one is rounded and the other is not. Thanks again!

**Comment by sckott** [comment]
asked for feedback in our forum, hopefully we'll get some feedback https://discuss.ropensci.org/t/cleaning-occurrence-data-your-feedback-wanted/475

**Comment by Pakillo** [comment]
Hi,

Maybe I'm too skeptic, but I'd also be suspicious of coordinates where *just one* of lat & long are rounded (without decimals). They may be right in the end, but I'd like to be able to flag and inspect them. So, I'd vote for having both 'AND' and 'OR' possibilities.

Thanks!

**Comment by vamsikrishna97** [comment]
Hi,
Please don't mind me asking this but shouldn't "coordinateUncertaintyInMeters" also be taken into consideration while flagging imprecise coordinates?

**Comment by sckott** [comment]
@vamsikrishna97 thanks for your input on this. 

Work so far on this has only dealt with the actual coordinate values themselves. 

But yes, `coordinateUncertaintyInMeters` if available could be used. I imagine a user might want to say e.g., 

> I want to flag any occurrences with `coordinateUncertaintyInMeters` greater than X value

**Comment by vamsikrishna97** [comment]
Exactly! we could flag any occurrences above a certain threshold for `coordinateUncertainityInMeters` and the same applies to `coordinatePrecision`.

 Actually, I am applying for GSOC biodiversity Data Cleaning and I was thinking of making a function for this

**Comment by sckott** [comment]
okay. open to PR' for that. 

might be able to add to the current fxn, or add a different one, not sure yet

**Comment by vamsikrishna97** [comment]
Hi,
We should be able to integrate this into the `coord_imprecise` itself but I think it'd be easier to understand for the user if it is a different fxn.
 I'll work on this and see how it pans out.
Thanks

**Comment by sckott** [comment]
sounds good

**Comment by sckott** [comment]
closing this one for now since this fxn does exist - #32 will continue any refinements
