### ISSUE TITLE
More use cases?

### ISSUE THREAD

**Issue by sckott** [ropensci/scrubr#2]
use cases are outlined in readme at top https://github.com/sckott/cleanoccs#cleanoccs

There's got to be other ones:
- round to user-defined number of decimal places of coordinates (from #5 )
- taxonomy based cleaning use cases:
  - collapse duplicates based on lowest level name (e.g., species)
  - collapse duplicates based on higher level taxonomic name (e..g, collapse all species within a family)
  - drop duplicates based on name
  - drop any records without names
- date based cleaning
  - drop records without dates
  - drop records without dates that can not be coerced to a real date
  - standardize dates
  - create date from other fields
- ...

**Comment by geneorama** [comment]
I hope you'll find these suggestions helpful.  They are based on my confusion when trying your package.

 1. Avoid `%>%` for the readme, unless it's necessary for `scrubr`.  Personally, I've never gotten comfortable with / embraced the `%>%` operator.  So I wasn't sure if `dp <- clean_df(smalldf) %>% dedup()` was equivalent to `dp <- clean_df(dedup(smalldf))` or `dp <- dedup(clean_df(smalldf))`, and I can't even remember the best way to look up `%>%`.  Why not make your examples showcase your functions directly, and let others put them into the frameworks they use?
 2. Provide some quick steps to convert the sparse matrix results back to a data.frame, and / or direct the user to the right help for the result (I wasn't sure if I should look at the help in `slam` or `Matrix`).
 3. Also, with `dedup` I was confused about whether the desired results should be 19 or 20 rows.  The "clean" result says `Size: 19 X 5`, but the `dedup` result is 20 rows.  You might want to clarify that there were no duplicates in the data until you added the 21st row (it's hard to eyeball for near duplicates). 

As an aside, I wish `dedup` returned a vector of indices or logicals to indicate "duplicated" in a manner that is consistent with the existing `duplicated` or `grep` / `grepl`; I think that would have been easier / less confusing.

**Comment by sckott** [comment]
@geneorama thanks for the feedback!

* I am happy to show examples of w/ and w/o pipes. I'll update the readme.  The thing coming before the pipe goes into the first argument of the next function after the pipe. 
* In _Provide some quick steps to convert the sparse matrix results back to a data.frame_ I'm not sure what you are referring to
* `dedup()` - Desired result at end of the readme eg is 19 rows, as the eg finds duplicates and removes them. However, I realized looking at it, that there should be an option to keep one of each grouping of duplicates. I'll open a new issue for that. In terms of returning a vector of logicals, we could do that, but I think it makes more sense to return the same object that was given to the function, with duplicates removed. Plus the vector of logicals doesn't give much information. E.g., we don't now, but in the attribute in the output of dedup, we can add more info on why a group of records were flagged as duplicates, etc. Maybe we can have a different function that returns a logical vector

**Comment by geneorama** [comment]
@sckott 
> Provide some quick steps to convert the sparse matrix results back to a data.frame

It was hard to be clear about this, because I was confused about the desired outcome (19 or 20 rows), which made it hard to make an example.  The example's "desired" outcome is 19 rows, but I think **my** desired outcome would be the 20 rows of non-duplicated data.  

I wasn't sure how to get a `data.frame` of the 20 observations "non duplicated" observations.  I think you would have to take the 19 observations, then `rbind` one observation from the `dups` attribute?  

I was also confused because I took the final outcome and forced it to be a data.frame and I misread the number of rows to be 20.  This really threw me, I couldn't figure out how it grew when I coerced it into a data.frame object. 

```R
## sample data, with the 10th record duplicated
## (no other duplicates or near duplicates)
df <- sample_data_1[c(1:20, 10), ]
## Now make row 21 a "near duplicate" of row 10
df[21, "key"] <- 1088954555

## Unique correctly identifies and removes the exact duplicates
nrow(unique(df))

## dedup correctly identifies and removes the exact and near duplicates 
## (unfortunately it completely removes them for now, and stuffs them into
## the dups attribute)
nrow(dedup(df))

##
## Now, here's was really confused....
##

## Make ds.  I'm calling it ds for "data sparse"
ds <- dedup(clean_df(df))

## ds has 19 rows
ds

## I wanted ds to be a data.frame... so I forced it to be a data.frame
class(ds) <- "data.frame"

## Printing ds looks like it has 20 rows because of the final row.name of 20
ds

```

The coercion above might not be great R code, but I wanted my result to be a `data.frame` and only a `data.frame` and I didn't know how else to get it there... I didn't try `as.data.frame` for because it already had the `data.frame` class.

**Comment by sckott** [comment]
I see. I did say [above](https://github.com/sckott/scrubr/issues/2#issuecomment-145112271) that yes, the expected result is 19 rows, _BUT_ I realize that that is not ideal, and perhaps the default should be to remove all but 1 of each duplicate group of records, which i'll change, see #10 

The output of `clean_df()`, `dedup()`, and all other fxns in this pkg is a data.frame, just with a few other classes attached. So you can treat it like any other data.frame. 

> Printing ds looks like it has 20 rows because of the final row.name of 20

Good catch. I'll make sure that row names are reset before giving data back, to avoid any confusion.
