### ISSUE TITLE
Filter by biome/ecoregion

### ISSUE THREAD

**Issue by sckott** [ropensci/scrubr#30]
via https://github.com/ropensci/rgbif/issues/133

**Comment by sckott** [comment]
@afredstonhermann what sources of biomes/ecoregions would you use/trust?

**Comment by afredstonhermann** [comment]
Great question, I think it depends if the user is more interested in the geographic area of the record (like me) or the actual ecoregion type. Either way I imagine it should be a set of polygons so we can just ID the polygon within which any georeferenced record falls. 

There are [global databases of ecoregions](http://maps.tnc.org/gis_data.html); I'm most familiar with the marine one (marine ecoregions of the world, MEOWs) but it looks like they've been developed for marine, freshwater, and terrestrial. Just found a [stackexchange thread](https://gis.stackexchange.com/questions/191258/global-shapefile-of-biomes-ecoregions) talking about some of the differences between ecoregion mapping approaches. 

The above might be really helpful for some people--there must be someone out there who wants to filter for only records in tropical dry forests!--but upon reflection, for my purposes it would really be easiest to just have a higher-level geographical classification than "country". Maybe something like continent on land, and major ocean region (Indian Ocean, Eastern Pacific, Caribbean, Mediterranean, etc.) for the oceans. This also seems maybe useful for other users, who want every record of rhinos on the African continent, or every Mediterranean tuna, etc.

**Comment by sckott** [comment]
thanks for these thoughts. i do think it's worth having a pkg do this kind of thing since I have had many people ask about how to do this. I think it belongs here rather than rgbif since rgbif is already complicated enough - and this will require probably leveraging spatial R pkgs (and their system libraries)

Makes sense to offer a number of different 1) data sources (as long as they are public data and avail. in an easy to user format) and 2) methods (e.g, filter by continent (`continent = "Africa"`), filter by ecoregion (`ecoregion_id = "some id"`))

a caveat about rgbif: in rgbif, GBIF does allow you to search by a well known text (WKT) area, so you could limit your search for example to an ecoregion. you'd have to make the WKT yourself though. And if the WKT is complex enough (lots of points) we may run into issues with the request being too large for GBIF to handle - however, I do think it will probably be easier to simply filter results by continent/ecoregion after pulling down gbif data

**Comment by afredstonhermann** [comment]
that all makes a lot of sense. let me know if you want me to test anything, and I'll probably be messing with this independently in the next week to come up with some geographic filters.

**Comment by afredstonhermann** [comment]
updating this with a couple other notes:
`robis::occurrence()` can be passed an area ID, a depth range, or a geometry, which I assume can pre-filter data before returning it (didn't test this though). sounds like this feature won't end up being part of `rgbif` but just wanted to point it out. 

someone on Twitter shared the [FAO marine boundaries dataset](http://www.fao.org/fishery/area/search/en) (go to *download shape file -> "FAO Statistical areas (Marine ) - GIS data (WFS - SHP)*), which has 16 or 17 different levels of spatial aggregation including one that is just four major global oceans. this is what I'm using to crop out points from GBIF right now.

**Comment by sckott** [comment]
thanks!

I'm not sure what the areaid actually uses within robis. do you know?  Unlikely that we'd be able to get GBIF to have an additional filter - but we could at least ask.  But i imagine they'd be reluctant to add something, because as you're discussed, there's many different ecoregion sources and at diff spatial scales, which would i imagine be too complex to support for them. 

Having a look at the FAO dataset. Where is the documentation for the differnt levels of spatial aggregation?

**Comment by sckott** [comment]
@afredstonhermann also, how would you and folks in your field select an ecoregion in R? Would you use a FID code, or some other code. Prefer to select a region by name?

**Comment by sckott** [comment]
started work on the `ecoregion` branch

**Comment by afredstonhermann** [comment]
I can't speak for the field but my personal preference is always to select by name if there is a list of options available in the package documentation... reduces risk of error and is clearer for future users relative to codes!
