### ISSUE TITLE
How to filter more than one ecoregion in the eco_region function

### ISSUE THREAD

**Issue by jenifferteles** [ropensci/scrubr#35]
Hello!
I’m not able to filter more than one ecoregion in the eco_region function.
I tried to use:
tmp <- eco_region (dframe(OcurrencesOK3), dataset = "meow", region = c('ECO_CODE_X:73','ECO_CODE_X:74','ECO_CODE_X:75'))

But it only filters the first ecoregion, how do I get it to filter all the selected ones?

Thank you!

**Comment by sckott** [comment]
Thanks for opening the issue @jenifferteles , i'll have a look

**Comment by sckott** [comment]
Please try again after reinstalling like `remotes::install_github("ropensci/scrubr")`, and it should work, let me know what happens

**Comment by jenifferteles** [comment]
Hello, @sckott!

It worked, thank you very much.
