### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by sckott** [ropensci/scrubr#5]
I have a first draft function for this https://github.com/sckott/cleanoccs/blob/master/R/dedup.R

I use a particular method, concatenating each row (all columns) into a single string. Then compare all rows against each other, all pairwise combinations, then allow user to set a tolerance, e.g., 0.9, where all strings that have a score of 0.9 or greater, will be dropped. 

I haven't thought about this deeply. What are better ways to do this?  i imagine we could allow multiple options as well.

**Comment by jarioksa** [comment]
I'm so much ahead of you in timezones that I may be too sleepy to grasp what you want to do. There are a couple of different task: removing duplicates and removing suspicious locations. Both could work by first rounding to user-defined number of decimal places of coordinates and using `duplicated()`. Finding bad coordinates could happen through `duplicated(rbind(bad_locations, my_locations))`. I haven't a list of of bad (or suspicious) locations, but I have tried `pruning` duplicates in https://github.com/jarioksa/biogeo/blob/master/R/occpmap.R

**Comment by sckott** [comment]
The approach I tried in this fxn is to just compare all fields for each row, which takes into account all data.  That is pretty blunt approach of course. 

> There are a couple of different task: removing duplicates and removing suspicious locations. 

What do you mean by `suspicious locations`?

> rounding to user-defined number of decimal places of coordinates 

right, i like that approach, that's a good one to add

**Comment by sckott** [comment]
related ropensci/spocc#92

**Comment by sckott** [comment]
ropensci/mapr#5

**Comment by sckott** [comment]
will probably go with current function for first CRAN push, and think about this further later
