### ISSUE TITLE
Literature - to look for ideas, etc. 

### ISSUE THREAD

**Issue by sckott** [ropensci/scrubr#7]
- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267104/  "A semi-automated workflow for biodiversity data retrieval, cleaning, and quality control"
- http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12209/abstract 
- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4452258/ "SDMdata: A Web-Based Software Tool for Collecting Species Occurrence Records"
- http://data.nbn.org.uk/recordcleaner/documentation/NBNRecordCleanerUserguide.pdf may be something of interest there

**Comment by Pakillo** [comment]
Not really literature, but another piece of software to clean occurrence records https://github.com/CIAT-DAPA/cwr_occurrencesvalidation. May be useful to have a look!

**Comment by sckott** [comment]
Thanks @Pakillo - there's lots of great ideas in there!
